name: Gems - Release to GitHub Packages
on: # yamllint disable-line rule:truthy
  release:
    # It's fine to trigger on every release because if we tag a release w/o
    # bumping the Gem version, RubyGems will reject it with an error that the
    # version is already live.
    types: [published]

jobs:
  release-gems:
    name: Release gems to pkg.github.com
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - run: |
          [ -d ~/.gem ] || mkdir ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":github: Bearer ${GITHUB_TOKEN}" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem install rake && rake gems:release
