name: Gems - Release to GitHub Packages
on: # yamllint disable-line rule:truthy
  release:
    # It's fine to trigger on every release because if we tag a release w/o
    # bumping the Gem version, RubyGems will reject it with an error that the
    # version is already live.
    types: [published]

jobs:
  release-pkg-gems:
    name: Release gems to pkg.github.com
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: bundler, name: bundler1, ecosystem: bundler }
          - { path: bundler, name: bundler2, ecosystem: bundler }
          - { path: cargo, name: cargo, ecosystem: cargo }
          - { path: common, name: common, ecosystem: common}
          - { path: composer, name: composer, ecosystem: composer }
          - { path: docker, name: docker, ecosystem: docker }
          - { path: elm, name: elm, ecosystem: elm }
          - { path: git_submodules, name: git_submodules, ecosystem: gitsubmodule }
          - { path: github_actions, name: github_actions, ecosystem: github-actions }
          - { path: go_modules, name: go_module, ecosystem: gomod }
          - { path: gradle, name: gradle, ecosystem: gradle }
          - { path: hex, name: hex, ecosystem: mix }
          - { path: maven, name: maven, ecosystem: maven }
          - { path: npm_and_yarn, name: npm_and_yarn, ecosystem: npm }
          - { path: nuget, name: nuget, ecosystem: nuget }
          - { path: pub, name: pub, ecosystem: pub }
          - { path: python, name: python, ecosystem: pip }
          - { path: python, name: python_slow, ecosystem: pip }
          - { path: swift, name: swift, ecosystem: swift }
          - { path: devcontainers, name: devcontainers, ecosystem: devcontainers }
          - { path: terraform, name: terraform, ecosystem: terraform }

    steps:
      - uses: actions/checkout@v4
      - uses: jstastny/publish-gem-to-github@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          working-directory: ${{ matrix.suite.path }}
  release-gems:
    name: Release gems to pkg.github.com
    runs-on: ubuntu-latest
    needs:
      - ci

    steps:
      - uses: actions/checkout@v4
      - uses: jstastny/publish-gem-to-github@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
